### ISSUE TITLE
Potential package naming conflicts with BAT...

### ISSUE THREAD

**Issue by oschulz** [mlkrock/BATsDistribution.jl#3]
Hi @mlkrock ,

I have a registered package [BAT.jl ](https://github.com/bat/BAT.jl) with a long history. I'm currently making it more modular, there's BATBase.jl now, and soon there will be a few more registered packages like BATPlotting, BATMCMCSampling, etc. BAT also defines some distributions, so there might be a BATDistributions as well (not sure about that yet).

A package named BATsDistribution.jl might be confusing in that context. Could you imagine changing the name if you plan to register the package? I don't mean to appear pushy (it's your package, of course), just want to avoid confusion in the ecosystem package namespace.

**Comment by cgeoga** [comment]
Hey @oschulz, thanks for the note. This is an unfortunate naming collision, sorry. We call this BATsDistribution because this is a (B)ulk (a)nd (T)ail(S) (emphasis on the S) distribution, which is a new distributional model. Would renaming it to BulkAndTails.jl be a satisfying resolution to you? We'd like to keep either BATs or BulkAndTails in the title considering that that is the name of the distribution, but BulkAndTails.jl seems like an equally clear and sensible name. We are actively trying to register the package, so if this would be satisfactory to you let us know and we'll do that.

**Comment by oschulz** [comment]
Hey, thanks so much! I like BulkAndTails.jl - I would say it's "smoother" than BATsDistribution.jl anyway.

Of course you should keep referring to them as BATs in the docs, if that the "official" acronym. Hard to completely avoid name clashes in science acronym namespace. :-)

**Comment by oschulz** [comment]
Maybe the actual Distribution type could be called `BulkAndTailsDist` or so? I would recommend not using something that ends on "s", since it can imply "plural" to new users.

**Comment by oschulz** [comment]
Unrelated question - I was looking for a very "bendable/flexible" modern distribution type recently, as an ingredient for normalizing flows. Do BATs (here I mean the plural ;-) ) have efficient `cdf` and `quantile` functions?

**Comment by mlkrock** [comment]
Hi @oschulz thanks for the suggestions, we have renamed accordingly. For your last question, first some clarification for readers: the distribution in this package, abbreviated as "BATs",  has flexible behavior in both tails, and is the first "Bulk-And-Tails" distribution we are aware of. Its cdf is efficient (closed form, AD-able in theory) but the quantile is not (just a root finder with the cdf). There are also some nonlinear constraints on the parameter space. So maybe the cdf  could be useful for the likelihood direction of the flow and quantile for the sampling direction of the flow?

**Comment by oschulz** [comment]
Thanks a lot for the rename, @mlkrock !

**Comment by oschulz** [comment]
> So maybe the cdf could be useful for the likelihood direction of the flow and quantile for the sampling direction of the flow

I guess so - the root finder in the quantile will make parallel use (e.g. on GPUs) difficult though.
